### ISSUE TITLE
Compat: Farmerʼs Respite

### ISSUE THREAD

**Issue by dhouck** [MehVahdJukaar/FarmersDelightRefabricated#46]
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.1

### Fabric Loader version

0.15.11

### Fabric API version

0.92.1+1.20.1

### Description

The game fails to load with Farmerʼs Delight Refabricated and Farmerʼs Respite.  Probably the latter needs to do some work, and either way it should probably be on [the add-on compatibility page](https://github.com/MehVahdJukaar/FarmersDelight/blob/1.20/information/Addons_And_Integrations.md), especially since Respite Creators already is.

### Steps to reproduce

1. Attempt to start the game
2. See a crash before the window opens

### Mod list

Quite a few; I havenʼt tested with the minimal set.  The error could be elsewhere, although disabling Farmerʼs Respite does let the game launch and behave normally.  But it seems like this is enough to add Farmerʼs Respite to the add-on compatibility page with a :question: status.

I can attempt to reproduce with the minimal set later if requested.

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
Compabitlity should be added from an addon to the mod, not vice versa. They are addons ater all.
The compat layer this mod has is not complete and cant really cover all cases, was more meant to be somehting to cover a handful of them since most just referenced just some FD classes in a simple way so that was easy to do and was meant more as something to ease in the transition. More complex mod like that one will require to be updated properly

**Comment by dhouck** [comment]
Yeah, I’m not asking for it to be updated; Iʼm just asking for it to be marked as not yet compatible.
